'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle
timmy=turtle.Turtle()
timmy.penup()
timmy.shape('turtle')
timmy.pensize(3) # width of pen line
timmy.speed(20)  # speed of drawing. Go fast to not waste time.
timmy.color("#00FA9A")
timmy.setpos(0,0)
timmy.pendown()
timmy.circle(100)
timmy.penup()
timmy.setpos(-50,185)
timmy.pendown()
timmy.goto(-50,15)
timmy.penup()
timmy.goto(-10,198)
timmy.pendown()
timmy.goto(-10,1)
timmy.penup()
timmy.goto(30,195)
timmy.pendown()
timmy.goto(30,5)
timmy.penup()
timmy.goto(-85,50)
timmy.pendown()
timmy.goto(85,50)
timmy.penup()
timmy.goto(-100,100)
timmy.pendown()
timmy.goto(100,100)
timmy.penup()
timmy.goto(-85,150)
timmy.pendown()
timmy.goto(85,150)
timmy.penup()
timmy.goto(150,50)
timmy.pendown()
timmy.circle(50)
timmy.penup()
timmy.goto(150,65)
timmy.pendown()
timmy.circle(10)
timmy.penup()
timmy.goto(150,110)
timmy.pendown()
timmy.circle(10)
timmy.penup()
timmy.goto(-98,120)
timmy.pendown()
timmy.goto(-130,100)
timmy.goto(-98,80)
timmy.penup()
timmy.goto(90,-100)
timmy.pencolor('#00FA9A')
timmy.write('Emma E. Moritz',font=("Emma", 12, "normal"))
turtle.exitonclick() #Keeps pycharm window open
